image_route:
  path:     /display
  controller: App\Controllers\ImageController::index
  methods:    GET

display_image_router:
  path:     /{image}
  controller: App\Controllers\ImageController::cropImage
  methods:    GET
  requirements:
    image: '^[^?]*\.(jpg|jpeg|gif|png|webp)'
